<?php

namespace App\Category\Filament\Resources\CategoryResource\Actions;

use Filament\Support\Enums\MaxWidth;

class CreateAction extends \App\Support\Filament\Actions\CreateAction
{
    /**
     * @return void
     */
    protected function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->modalWidth(MaxWidth::TwoExtraLarge)
            ->form(new Forms\Form()->configure())
            ->mutateFormDataUsing(function ($data) {
                return array_merge($data, [
                    'created_by' => auth()->id(),
                ]);
            });
    }
}
