<?php

namespace App\Category\Filament\Resources\CategoryResource\Actions;

use Filament\Support\Enums\MaxWidth;

class ModifyAction extends \App\Support\Filament\Tables\Actions\ModifyAction
{
    /**
     * @return void
     */
    protected function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->modalWidth(MaxWidth::TwoExtraLarge)
            ->form(new Forms\Form()->configure());
    }
}
